config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "sessions", only: [:create]

  resources :users, controller: "users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  resources :users
  

  root "pages#index"
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :listings, controller: "listings"
  post 'listings/search' => 'listings#search'
  resources :reservations, controller: "reservations"
  get '/reservations/book/:id' => 'reservations#book'
  resources :tags, controller: "tags"
  get '/tags/filters' => 'tags#filters'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
   belongs_to :user
   def self.create_with_omniauth(auth_hash)
     auth = Authentication.new(provider: auth_hash["provider"], uid: auth_hash["uid"], token: auth_hash["credentials"]["token"])
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
	mount_uploaders :avatars, AvatarUploader

	attr_accessor :tag
	belongs_to :user
	has_many :taglinks, dependent: :destroy
	has_many :tags, :through => :taglinks
	has_many :reservations, dependent: :destroy

	enum place_type: ["Entire home","Private room","Shared room"]

	def booked_dates
		booked = []
		self.reservations.each do |reserve|
			booked<<(reserve.start_date..reserve.end_date).map(&:to_s)
		end
		booked.flatten.uniq
	end
end

app/models/page.rb
class Page < ApplicationRecord
	paginates_per 5
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :user
	belongs_to :listing
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :listings, :through => :taglinks
	has_many :taglinks, dependent: :destroy

end

app/models/taglink.rb
class Taglink < ApplicationRecord
	belongs_to :listing
	belongs_to :tag

	validates :tag_id, uniqueness: {:scope => :listing}
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  mount_uploader :avatar, AvatarUploader
  
  has_many :authentications, dependent: :destroy
  has_many :listings, dependent: :destroy
  has_many :reservations, dependent: :destroy
  validates :email, uniqueness: true

  @@auth_login = false

  def self.create_with_auth_and_hash(authentication, auth_hash)
      @@auth_login = true
      user = User.new(name: auth_hash["info"]["name"], email: auth_hash["extra"]["raw_info"]["email"])
      if user.save
        user.authentications << (authentication)
      else
        user=User.find_by(email: auth_hash["extra"]["raw_info"]["email"])
        user.name = auth_hash["info"]["name"]
      end      
      return user
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    if @@auth_login
      return true
    else
      return false
    end
     @@auth_login = false
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :find_listings, only: [:show]
	def index
	end

	def new
		@listing = Listing.new
		@taglink = Taglink.new
		render template: "listings/new"	
	end

	def create
		@listing = Listing.create(listings_from_params)
		@listing.update(user_id: current_user.id)
		params["listing"]["tag"].each do |key,value|
			next if value == "0"
			tag = Tag.find_by(name: key)
			Taglink.create(listing_id: @listing.id,tag_id: tag.id)
		end
		redirect_to listing_path(@listing)
	end

	def show
		session[:listing_id] = params[:id]
	end

	def search
		keyword = params[:search].titleize
	    @listings = Listing.where("city LIKE ?", "#{keyword}%")
	    @listings = Listing.all if params[:search] == ""
        respond_to do |format|
      		format.js 
        end 
	end

	def date
		@listing = Listing.find(params[:id])
		respond_to do |format|
			format.js
		end
	end

	private

	def find_listings
		@listing = Listing.find(params[:id])
	end

	def listings_from_params
	    params.require(:listing).permit(:name,:description,:country,:state,:city,:zipcode,:street,:place_type,:property_type,:guest_no,:room_no,:bed_no,:price,{avatars: []})
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
		@listings = Listing.page params[:page]
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	def create
		if !signed_in?
			redirect_to sign_in_path
			flash[:info] = "Please log in before booking"
		else
			@reserve = Reservation.new(reservation_from_param)
			@reserve.save
			@reserve.update_columns(user_id: current_user.id)
			@listing = Listing.find(session[:listing_id])
			flash[:success] = "Congratulations! Your booking is succcesful!"
			redirect_to listing_path(@listing)
		end
	end

	def reservation_from_param
		params.require(:reservation).permit(:start_date,:end_date,:listing_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  def create
    @user = authenticate(params)
    sign_in(@user) do |status|
      if status.success?
      	flash[:notice] = "Successfully signed in"
        redirect_back_or url_after_create
      else
        flash.now.notice = status.failure_message
        render template: "sessions/new", status: :unauthorized
      end
    end
  end


  def create_from_omniauth
    auth_hash = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) || Authentication.create_with_omniauth(auth_hash)
    if authentication.user
      user = authentication.user 
      authentication.update_token(auth_hash)
      @next = root_url
      @notice = "Signed in!"
    else
      user = User.create_with_auth_and_hash(authentication, auth_hash)
      @next = root_url   
      @notice = "Signed in!"
    end
    sign_in(user)
    redirect_to @next, :notice => @notice
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
	def new
	    @user = User.new
	    render template: "users/new"
	end

	def create
	    @user = User.new(user_from_params)
	    if @user.save
	      sign_in @user
	      flash[:notice] = "Successfully signed up"
	      redirect_back_or url_after_create
	    else
	    	# flash[:notice] = @user.errors.full_messages.first
	      @message = @user.errors.full_messages.first
	      respond_to do |format|
	      	format.js
	      	format.html
	      end
	    end
	end

	def show
		
	end

	private

	def user_from_params
	    params.require(:user).permit(:name,:email,:password,:avatar)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
	
	def place_type(listing)
		case listing.place_type
		when 1
		"Entire home"
		when 2
		"Private room"
		when 3
		"Shared room"
		end
	end

	def bed_no(listing)
		bed_no = listing.bed_no
		if bed_no == 1
			"1 bed"
		else
			"#{bed_no} beds"
		end
	end

	def guest_no(listing)
		guest_no = listing.guest_no
		if guest_no == 1
			"1 guest"
		else
			"#{guest_no} guests"
		end
	end

	def room_no(listing)
		room_no = listing.room_no
		if room_no == 1
			"1 room"
		else
			"#{room_no} rooms"
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div id="header">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <%=link_to "PairBnB", root_path, class: "navbar-brand"%>
      </div>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-align-justify"></span></a>
          <ul class="dropdown-menu">
            <li><%=link_to "Create a new listing", new_listing_path%><br></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li>
      </ul>

    <%if request.fullpath == "/"%>
      <%=form_tag "/listings/search", class: "navbar-form navbar-left", remote: true do%>
      <div class="form-group">
        <%=text_field_tag :search, nil,placeholder: "Search city",class: "form-control"%>
      </div>
        <%= submit_tag "Find",class: "btn btn-default", :style => "display: none;"%>
        <button data-toggle="modal" data-target="#filterModal" class="btn btn-default">More Filters</button>
      <%end%>

    <%end%>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? -%>
          <li><%= link_to user_path(current_user) do%>
              <i class="glyphicon glyphicon-user"></i> <%=current_user.name%>
              <%end%>
            </li> 
          <li><%= link_to sign_out_path, method: :delete do%>
            <i class="glyphicon glyphicon-log-in"></i> Sign Out
            <%end%>
          </li>  
        <% else -%>
          <li><%= link_to sign_up_path do%>
            <i class="glyphicon glyphicon-user"></i> Sign Up
            <%end%>
          </li>
          <li><%= link_to sign_in_path do%>
            <i class="glyphicon glyphicon-log-in"></i> Sign In
            <%end%>
          </li>
        <% end -%>
      </ul>
    </div>
  </nav>
</div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"  class="alert alert-success alert-dismissable">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <%=h value %></div>
    <% end %>
  </div>
  <div id="listing-list" class="container"%>
  <%= yield %>
  </div>
</body>
</html>

app/views/listings/_carousel.html.erb
<%if @listing.avatars.present?%>
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
  </ol>

  <!-- Wrapper for slides -->
 <div class="carousel-inner">
     <div class="item active">
      <%= image_tag @listing.avatars[0].url%>
    </div>

  <%(@listing.avatars.length-1).times do |t|%>
        <div class="item">
          <%= image_tag @listing.avatars[t+1].url%>
        </div>
  <%end%>

  </div>
  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<%end%>

app/views/listings/_form.html.erb
<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :description %>
  <%= form.text_area :description,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :country %>
  <%= form.text_field :country,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :state %>
  <%= form.text_field :state,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :city %>
  <%= form.text_field :city,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :zipcode %>
  <%= form.number_field :zipcode,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :street %>
  <%= form.text_field :street,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :room_type %>
  <%= form.select :place_type, options_for_select([["Select Room Type",""]]+Listing.place_types.to_a) ,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :property_type %>
  <%= form.select :property_type, options_for_select([["Select Property Type",""]]+ Listing.all.pluck(:property_type).uniq) ,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :number_of_guests %>
  <%= form.number_field :guest_no,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :number_of_rooms %>
  <%= form.number_field :room_no,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :number_of_beds %>
  <%= form.number_field :bed_no,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :price %>
  <%= form.number_field :price,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :listing_pictures %>
  <%= form.file_field :avatars,multiple: true,class: "form-control" %>
</div>

app/views/listings/new.html.erb
<div class="new_listing_page">
<h2><%= t("New listing") %></h2>

<%= form_for @listing,remote: true do |form|%>
<%= render partial: '/listings/form', object: form %>



<%= form.fields_for :tag, :label => false do |f|%>
Amenities
<%Tag.where(tagtype: "Amenities").each do |tag|%>
	<div>
	<%= f.check_box tag.name.to_sym%>
	<%= f.label tag.name%>
	</div>
<%end%>
Facilities
<%Tag.where(tagtype: "Facilities").each do |tag|%>
	<div>
	<%= f.check_box tag.name.to_sym%>
	<%= f.label tag.name%>
	</div>
<%end%>
House Rules
<%Tag.where(tagtype: "House Rules").each do |tag|%>
	<div>
	<%= f.check_box tag.name.to_sym%>
	<%= f.label tag.name%>
	</div>
<%end%>
Host Language
<%Tag.where(tagtype: "Host Language").each do |tag|%>
	<div>
	<%= f.check_box tag.name.to_sym%>
	<%= f.label tag.name%>
	</div>
<%end%>



<div class="submit-field">
  <%= form.submit "Create a new listing",class: "btn btn-default"%>
</div>
<%end%>
<% end %>
</div>

app/views/listings/search.js.erb
$('#listing-list').html("<%= j render 'pages/list', object:@listings %>")

app/views/listings/show.html.erb
<%= render partial: 'carousel' %>

<h1><%=@listing.name%></h1>
<%=@listing.city+", "+@listing.state+", "+@listing.country%><br>
<%=@listing.place_type%>&nbsp;
<%=guest_no(@listing)%>&nbsp;
<%=room_no(@listing)%>&nbsp;
<%=bed_no(@listing)%>
<h3>About this listing</h3>
<p><%=@listing.description%></p>
<button data-toggle="modal" data-target="#myModal" class="btn btn-default">Book Now!</button>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Place a Booking</h4>
      </div>
      <div class="modal-body">
        <%= render partial: '/reservations/form',locals: {reserve: Reservation.new} %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<%= javascript_tag do%>
  $('#datepicker').datepicker({
    dateFormat: "yy-mm-dd",
    minDate: new Date(),
    beforeShowDay: function(date){
      var string = jQuery.datepicker.formatDate('yy-mm-dd', date);
      return [ <%=raw @listing.booked_dates%>.indexOf(string) == -1 ]
    },
    onSelect: function(date){
      $("#datepicker2").datepicker('option','minDate',date)
    }
  });

  $('#datepicker2').datepicker({
    dateFormat: "yy-mm-dd",
    beforeShowDay: function(date){
      var string = jQuery.datepicker.formatDate('yy-mm-dd', date);
      return [ <%=raw @listing.booked_dates%>.indexOf(string) == -1 ]
    }
  });
<%end%>

app/views/pages/_list.html.erb
<div class="col-md-10 col-sm-10">
<div class="row" id ="row">
<% @listings.each do |list|%>

<div class="all_listing well col-xs-12 col-sm-4 col-md-2" id="/listings/<%=list.id%>" style="cursor:pointer">
	RM<%=list.price%>&nbsp;
	<%=list.name%><br>
	<%=list.city+", "+list.state+", "+list.country%><br>
	<%=list.place_type%>
	&nbsp;
	<%=bed_no(list)%> 
</div>

<%end%>
</div>
</div>

app/views/pages/index.html.erb
<div class = "row">
<div class="col-md-1 col-sm-1"></div>
  <div id="listing-list">
  	<%= render partial: 'list' %>
  </div>
<div class="col-md-1 col-sm-1"></div>
</div>


  <div id="filterModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Apply filters</h4>
        </div>
        <div class="modal-body">
          <%= render partial: '/tags/all' %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

app/views/reservations/_form.html.erb
<%=form_for reserve do |form|%>
	<div class="form-group">
	  <%= form.label :start_date %>
	  <%= form.text_field :start_date,id: "datepicker",class: "form-control" %>
	</div>

	<div class="form-group">
	  <%= form.label :end_date %>
	  <%= form.text_field :end_date,id: "datepicker2",class: "form-control" %>
	</div>

	<div class="form-group">
	  <%= form.hidden_field :listing_id, value: session[:listing_id]%>
	</div>

	<%=form.submit "Book",class: "btn btn-default"%>
<%end%>

app/views/tags/_all.html.erb
<%=form_tag ('/tags/filters') do %>

	<%= select_tag "room_type", options_for_select([["Select Room Type",""]]+Listing.place_types.to_a),role: "button",class: "btn btn-default" %><br>

	Amenities
	<%Tag.where(tagtype: "Amenities").each do |tag|%>
		<div>
		<%= check_box_tag tag.name.to_sym%>
		<%= label_tag tag.name%>
		</div>
	<%end%>

	Facilities
	<%Tag.where(tagtype: "Facilities").each do |tag|%>
		<div>
		<%= check_box_tag tag.name.to_sym%>
		<%= label_tag tag.name%>
		</div>
	<%end%>

	House Rules
	<%Tag.where(tagtype: "House Rules").each do |tag|%>
		<div>
		<%= check_box_tag tag.name.to_sym%>
		<%= label_tag tag.name%>
		</div>
	<%end%>

	Host Language
	<%Tag.where(tagtype: "Host Language").each do |tag|%>
		<div>
		<%= check_box_tag tag.name.to_sym%>
		<%= label_tag tag.name%>
		</div>
	<%end%>
<%end%>

app/views/users/_form.html.erb
<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email',class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :password %>
  <%= form.password_field :password,class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :profile_picture %>
  <%= form.file_field :avatar,class: "form-control" %>
</div>

app/views/users/create.js.erb
$("h2").before("<div class=\"alert alert-danger\">"+
	"<a href=\"#\" class=\"close\" data-dismiss=\"alert\" aria-label=\"close\">&times;</a>"+
	"<%=j @message%></div>")

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user,remote: true do |form|%>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit "Sign Up",class: "btn btn-default"%>
    </div>

  <% end %>
</div>

app/views/users/show.html.erb
<%=current_user.name%><br><br>

Your listings:<br><br>
<% current_user.listings.each do |list|%>
<div class="all_listing" id="/listings/<%=list.id%>" style="cursor:pointer">
	RM<%=list.price%>&nbsp;
	<%=list.name%><br>
	<%=list.city+", "+list.state+", "+list.country%><br>
	<%=list.place_type%>
	&nbsp;
	<%=bed_no(list)%> 
</div>
	<br>
<%end%>


Your bookings:<br><br>
<% current_user.reservations.each do |reserve|%>
	Start date: <%=reserve.start_date%>&nbsp;
	End date: <%=reserve.end_date%><br>
	<%property = reserve.listing%>
	RM<%=property.price%>&nbsp;
	<%=property.name%><br>
	<%=property.city+", "+property.state+", "+property.country%><br>
	<%=property.place_type%>&nbsp;
	<%=bed_no(property)%> 
</div>
	<br><br>
<%end%>